
proxies:
  - name: "Akamai Connected Cloud - 1961.76 Mbps"
    type: trojan
    server: "104.22.5.240"
    port: 443
    password: "e9f0702f-c211-4b8e-a827-c0135962d805"
    security: "tls"
    sni: "free.c-stuff.Web.id"
    skip-cert-verify: true
    network: "ws"
    ws-opts:
      path: "/Free/TG-at-BitzBlack/172.232.239.151-587"
      host: "free.c-stuff.Web.id"
