name: V2Ray Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget golang

    - name: Download and Install V2Ray
      run: |
        wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip v2ray-linux-64.zip
        sudo mv v2ray-linux-64/v2ray /usr/local/bin/
        sudo mv v2ray-linux-64/v2ctl /usr/local/bin/
        sudo mv v2ray-linux-64/geoip.dat /usr/local/bin/
        sudo mv v2ray-linux-64/geosite.dat /usr/local/bin/
        sudo chmod +x /usr/local/bin/v2ray
        sudo chmod +x /usr/local/bin/v2ctl

    - name: Run V2Ray Configuration
      run: |
        # Buat file konfigurasi
        echo '{
          "outbounds": [
            {
              "protocol": "trojan",
              "settings": {
                "servers": [
                  {
                    "address": "ava.game.naver.com",
                    "port": 443,
                    "password": "aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1",
                    "email": ""
                  }
                ]
              }
            }
          ],
          "inbounds": [
            {
              "port": 1080,
              "protocol": "socks",
              "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
              }
            }
          ]
        }' > config.json

        # Jalankan V2Ray
        v2ray -config ./config.json &

    - name: Test Connection
      run: |
        # Menguji koneksi
        PROXY="socks5h://127.0.0.1:1080"
        curl -x $PROXY http://www.msftconnecttest.com/connecttest.txt
