name: Xray Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget curl jq

    - name: Get Latest Xray Release URL
      id: get_url
      run: |
        ARCH="linux-arm64.zip"  # Menggunakan arsitektur ARM64
        
        # Dapatkan respons API
        RESPONSE=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest)
        echo "$RESPONSE"  # Tampilkan respons untuk debugging

        # Dapatkan URL unduhan untuk arsitektur yang sesuai
        XRAY_URL=$(echo "$RESPONSE" | jq -r ".assets[] | select(.name | contains(\"$ARCH\")) | .browser_download_url")

        # Periksa apakah URL berhasil diambil
        if [ -z "$XRAY_URL" ]; then
          echo "URL unduhan tidak ditemukan. Pastikan nama file sudah benar."
          exit 1
        fi

        echo "::set-output name=url::$XRAY_URL"  # Mengatur output URL

    - name: Download and Install Xray
      run: |
        # Mengambil URL dari langkah sebelumnya
        XRAY_URL=${{ steps.get_url.outputs.url }}

        # Unduh Xray
        wget $XRAY_URL
        
        # Ambil nama file dari URL
        XRAY_FILE=$(basename $XRAY_URL)

        # Ekstrak Xray
        unzip $XRAY_FILE
        
        # Buat direktori proxies jika belum ada
        mkdir -p proxies
        
        # Pindahkan biner Xray ke folder proxies
        mv xray proxies/
        chmod +x proxies/xray

    - name: Run Xray Configuration
      run: |
        # Buat file konfigurasi
        echo '{
          "outbounds": [
            {
              "protocol": "trojan",
              "settings": {
                "servers": [
                  {
                    "address": "ava.game.naver.com",
                    "port": 443,
                    "password": "aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1",
                    "email": ""
                  }
                ]
              }
            }
          ],
          "inbounds": [
            {
              "port": 1080,
              "protocol": "socks",
              "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
              }
            }
          ]
        }' > config.json

        # Jalankan Xray dari folder proxies
        ./proxies/xray -config ./config.json &

    - name: Test Connection
      run: |
        # Menguji koneksi
        PROXY="socks5h://127.0.0.1:1080"
        curl -x $PROXY http://www.msftconnecttest.com/connecttest.txt
