name: Update subscriptions

on:
  schedule:
    - cron: "0 */23 * * *"  # Setiap 23 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pyyaml speedtest-cli aiohttp tqdm

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Xray Latest Release
        id: get_xray
        run: |
          VERSION=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r .tag_name)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Install Xray
        run: |
          wget "https://github.com/XTLS/Xray-core/releases/download/${{ env.VERSION }}/xray-linux-64.zip"
          unzip xray-linux-64.zip
          sudo mv xray /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray

      - name: Run Python script
        run: |
          python3 main.py || { echo "Script failed"; exit 1; }

      - name: Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add proxies/
          git commit -m "Update subscriptions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
