name: Xray Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget curl jq

    - name: Download and Install Xray
      run: |
        # Dapatkan URL unduhan terbaru untuk Xray
        XRAY_URL=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r ".assets[] | select(.name | test(\"linux-amd64.zip\")) | .browser_download_url")

        # Periksa apakah URL berhasil diambil
        if [ -z "$XRAY_URL" ]; then
          echo "URL unduhan tidak ditemukan. Pastikan nama file sudah benar."
          exit 1
        fi

        # Unduh Xray
        wget $XRAY_URL
        
        # Ambil nama file dari URL
        XRAY_FILE=$(basename $XRAY_URL)

        # Ekstrak dan instal Xray
        unzip $XRAY_FILE
        sudo mv xray /usr/local/bin/
        sudo chmod +x /usr/local/bin/xray

    - name: Run Xray Configuration
      run: |
        # Buat file konfigurasi
        echo '{
          "outbounds": [
            {
              "protocol": "trojan",
              "settings": {
                "servers": [
                  {
                    "address": "ava.game.naver.com",
                    "port": 443,
                    "password": "aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1",
                    "email": ""
                  }
                ]
              }
            }
          ],
          "inbounds": [
            {
              "port": 1080,
              "protocol": "socks",
              "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
              }
            }
          ]
        }' > config.json

        # Jalankan Xray
        xray -config ./config.json &

    - name: Test Connection
      run: |
        # Menguji koneksi
        PROXY="socks5h://127.0.0.1:1080"
        curl -x $PROXY http://www.msftconnecttest.com/connecttest.txt
